# base image
FROM node:10.13-alpine

# set working directory
WORKDIR /usr/src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

RUN npm install

COPY . /usr/src/app

# start app
CMD ["npm", "start"]
